/* Generated by Yosys 0.20+45 (git sha1 029c2785e, clang  -fPIC -Os) */

module iiitb_sd_fsm(sequence_in, clock, reset, detector_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input clock;
  wire clock;
  wire [2:0] current_state;
  output detector_out;
  wire detector_out;
  wire [2:0] next_state;
  input reset;
  wire reset;
  input sequence_in;
  wire sequence_in;
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(_25_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(_26_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor3_1 _46_ (
    .A(_24_),
    .B(_28_),
    .C(_29_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__clkinv_1 _47_ (
    .A(_40_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o21bai_1 _48_ (
    .A1(_26_),
    .A2(_30_),
    .B1_N(_24_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o211ai_1 _49_ (
    .A1(_24_),
    .A2(_40_),
    .B1(_28_),
    .C1(_29_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__o21ai_0 _50_ (
    .A1(_28_),
    .A2(_31_),
    .B1(_32_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__and2b_2 _51_ (
    .A_N(_40_),
    .B(_24_),
    .X(_33_)
  );
  sky130_fd_sc_hd__o211ai_1 _52_ (
    .A1(_25_),
    .A2(_26_),
    .B1(_24_),
    .C1(_30_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nand2_1 _53_ (
    .A(_26_),
    .B(_40_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o211a_1 _54_ (
    .A1(_25_),
    .A2(_33_),
    .B1(_34_),
    .C1(_35_),
    .X(_37_)
  );
  sky130_fd_sc_hd__nor4_1 _55_ (
    .A(_24_),
    .B(_26_),
    .C(_28_),
    .D(_30_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__clkinv_1 _56_ (
    .A(_39_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__clkinv_1 _57_ (
    .A(_39_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__clkinv_1 _58_ (
    .A(_39_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__dfrtp_1 _59_ (
    .CLK(clock),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(_41_)
  );
  sky130_fd_sc_hd__dfrtp_1 _60_ (
    .CLK(clock),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(_42_)
  );
  sky130_fd_sc_hd__dfrtp_1 _61_ (
    .CLK(clock),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(_43_)
  );
  assign _24_ = current_state[0];
  assign _25_ = current_state[1];
  assign _26_ = current_state[2];
  assign detector_out = _27_;
  assign _40_ = sequence_in;
  assign next_state[0] = _36_;
  assign next_state[1] = _37_;
  assign next_state[2] = _38_;
  assign _39_ = reset;
  assign _41_ = _21_;
  assign _42_ = _22_;
  assign _43_ = _23_;
endmodule
